#!/bin/bash
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft1-2.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft1-3.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft1-4.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft1-5.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft1-6.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft1-7.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft2-1.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft2-3.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft2-4.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft2-5.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft2-6.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft2-7.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft3-1.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft3-2.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft3-4.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft3-5.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft3-6.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft3-7.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft4-1.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft4-2.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft4-3.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft4-5.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft4-6.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft4-7.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft5-1.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft5-2.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft5-3.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft5-4.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft5-6.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft5-7.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft6-1.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft6-2.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft6-3.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft6-4.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft6-5.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft6-7.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft7-1.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft7-2.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft7-3.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft7-4.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft7-5.yaml --overwrite
uv run python src/data_processing/combine_datasets.py configs/data_generation/pftset/combine_pft7-6.yaml --overwrite