#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l3.yaml --overwrite
#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l4.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l5.yaml --overwrite
#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l6.yaml --overwrite
#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l3_na.yaml --overwrite
#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l4_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l5_na.yaml --overwrite
#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l6_na.yaml --overwrite
#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l3_raw.yaml --overwrite
#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l4_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l5_raw.yaml --overwrite
#uv run python src/analysis/visualize_pca_3d_timeline.py /configs/analysis_pca_timeline/ftset/pt1-1/distance_firstcity_last_and_trans_l6_raw.yaml --overwrite
