#!/bin/bash
cd 
uv run python src/analysis/analyze_representations_higher.py configs/revision/exp3/representation_extraction/pt1_wide/distance_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/analyze_representations_higher.py configs/revision/exp3/representation_extraction/pt1_wide_ftwb1/distance_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/analyze_representations_higher.py configs/revision/exp3/representation_extraction/pt1_wide_ftwb2/trianglearea_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/analyze_representations_higher.py configs/revision/exp3/representation_extraction/pt1_wide_ftwb3/angle_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/analyze_representations_higher.py configs/revision/exp3/representation_extraction/pt1_wide_ftwb4/compass_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/analyze_representations_higher.py configs/revision/exp3/representation_extraction/pt1_wide_ftwb5/inside_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/analyze_representations_higher.py configs/revision/exp3/representation_extraction/pt1_wide_ftwb6/perimeter_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/analyze_representations_higher.py configs/revision/exp3/representation_extraction/pt1_wide_ftwb7/crossing_firstcity_last_and_trans_l5.yaml --overwrite
