#!/bin/bash
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-1/distance_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-1/distance_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-1/distance_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-2/angle_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-2/angle_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-2/angle_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-3/inside_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-3/inside_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-3/inside_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-4/crossing_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-4/crossing_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-4/crossing_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-5/trianglearea_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-5/trianglearea_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-5/trianglearea_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-6/compass_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-6/compass_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-6/compass_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-7/perimeter_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-7/perimeter_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-7/perimeter_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-8/angle_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-8/angle_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-8/angle_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-9/compass_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-9/compass_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-9/compass_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-10/angle_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-10/angle_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-10/angle_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-11/compass_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-11/compass_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-11/compass_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-12/crossing_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-12/crossing_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-12/crossing_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-13/distance_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-13/distance_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-13/distance_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-14/crossing_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-14/crossing_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-14/crossing_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-15/compass_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-15/compass_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-15/compass_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-16/inside_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-16/inside_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-16/inside_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-17/angle_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-17/angle_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-17/angle_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-18/compass_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-18/compass_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-18/compass_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-19/distance_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-19/distance_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-19/distance_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-20/perimeter_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-20/perimeter_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-20/perimeter_firstcity_last_and_trans_l5_raw.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-21/angle_firstcity_last_and_trans_l5.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-21/angle_firstcity_last_and_trans_l5_na.yaml --overwrite
uv run python src/analysis/visualize_pca_3d_timeline.py /configs/revision/exp1/pca_timeline/pt1_original_ftwb2-21/angle_firstcity_last_and_trans_l5_raw.yaml --overwrite
