#!/bin/bash
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-1_vs_pt3-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-1_vs_pt3-7_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-1_vs_pt3-7_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-2_vs_pt3-3_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-3_vs_pt3-4_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-4_vs_pt3-5_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-5_vs_pt3-6_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt3-6_vs_pt3-7_seed2_l6.yaml --overwrite
