#!/bin/bash
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-2_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-3_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-6_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-1_vs_pt2-7_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-3_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_same_seed_nonoverlap_l346/cka_pt2-2_vs_pt2-4_l4.yaml --overwrite
