#!/bin/bash
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-2/multi_4M_no_atlantis_30ep_pad_probe0-2_l0.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-2/multi_4M_no_atlantis_30ep_pad_probe0-2_l1.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-2/multi_4M_no_atlantis_30ep_pad_probe0-2_l2.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-2/multi_4M_no_atlantis_30ep_pad_probe0-2_l3.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-2/multi_4M_no_atlantis_30ep_pad_probe0-2_l4.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-2/multi_4M_no_atlantis_30ep_pad_probe0-2_l5.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-2/multi_4M_no_atlantis_30ep_pad_probe0-2_l6.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-3/multi_4M_no_atlantis_30ep_pad_probe0-3_l0.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-3/multi_4M_no_atlantis_30ep_pad_probe0-3_l1.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-3/multi_4M_no_atlantis_30ep_pad_probe0-3_l2.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-3/multi_4M_no_atlantis_30ep_pad_probe0-3_l3.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-3/multi_4M_no_atlantis_30ep_pad_probe0-3_l4.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-3/multi_4M_no_atlantis_30ep_pad_probe0-3_l5.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-3/multi_4M_no_atlantis_30ep_pad_probe0-3_l6.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-4/multi_4M_no_atlantis_30ep_pad_probe0-4_l4.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-4/multi_4M_no_atlantis_30ep_pad_probe0-4_l5.yaml --overwrite
uv run python /n/home12/cfpark00/WM_1/src/analysis/analyze_representations.py /n/home12/cfpark00/WM_1/configs/analysis_representation/multi_pretrain_no_atlantis_30ep_pad/0-4/multi_4M_no_atlantis_30ep_pad_probe0-4_l6.yaml --overwrite