#!/bin/bash
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed1_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_seed2_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-3_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-3_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed1_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_seed2_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-4_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed1_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed1_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed1_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed1_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed1_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed1_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed1_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed2_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed2_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed2_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed2_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed2_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_seed2_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-5_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_seed1_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_seed1_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_seed1_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_seed1_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_seed2_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_seed2_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_seed2_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-6_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-7_seed1_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-7_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt2-7_vs_pt2-7_seed2_l5.yaml --overwrite
