#!/bin/bash
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-1_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-2_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-2_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-3_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-3_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed1_vs_pt3-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-2_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-2_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-3_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-3_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_seed2_vs_pt3-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-1_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-1_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-2_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-2_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-3_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-3_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-1_vs_pt3-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-2_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-3_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-3_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed1_vs_pt3-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-3_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-3_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_seed2_vs_pt3-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-2_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-2_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-3_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-3_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all_l5/cka_pt3-2_vs_pt3-7_seed2_l5.yaml --overwrite
