#!/bin/bash
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-1_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-2_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-2_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-2_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-2_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_seed2_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-1_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-1_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-2_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-2_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-2_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_seed2_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-2_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-2_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-3_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-2_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed1_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed2_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed2_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed2_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed2_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed2_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_seed2_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-5_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_seed1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_seed1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_seed1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_seed2_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_seed2_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_seed2_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-6_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-7_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-7_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-7_vs_pt2-7_seed2_l3.yaml --overwrite
