#!/bin/bash
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-3_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-3_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-4_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-5_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-6_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed1_vs_pt2-7_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-4_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-5_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-6_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_seed2_vs_pt2-7_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-3_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-4_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-5_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-6_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-3_vs_pt2-7_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-4_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-4_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-4_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-4_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-5_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-6_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed1_vs_pt2-7_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed1_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed1_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed1_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed1_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed2_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed2_l4.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed2_l5.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-5_seed2_l6.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-6_l3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp2/cka_analysis_all/cka_pt2-4_seed2_vs_pt2-6_l4.yaml --overwrite
