#!/bin/bash
cd 
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-4_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-5/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-5_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-5_seed3/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-6/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-6_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-6_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-7/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-7_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-3_vs_pt1-7_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-4_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-4_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-5/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-5_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-5_seed3/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-6/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-6_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-6_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-7/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-7_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed1_vs_pt1-7_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed2_vs_pt1-4_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed2_vs_pt1-5/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed2_vs_pt1-5_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-4_seed2_vs_pt1-5_seed3/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-5/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-5_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-5_seed3/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-6/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-6_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-6_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-7/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-7_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-5_vs_pt1-7_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed1_vs_pt1-6_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed1_vs_pt1-6_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed1_vs_pt1-7/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed1_vs_pt1-7_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed1_vs_pt1-7_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed2_vs_pt1-6_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed2_vs_pt1-7/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed2_vs_pt1-7_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_seed2_vs_pt1-7_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_vs_pt1-6/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_vs_pt1-6_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_vs_pt1-6_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_vs_pt1-7/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_vs_pt1-7_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-6_vs_pt1-7_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-7_seed1_vs_pt1-7_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-7_seed1_vs_pt1-7_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-7_seed2_vs_pt1-7_seed2/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-7_vs_pt1-7/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-7_vs_pt1-7_seed1/layer3.yaml --overwrite
uv run python src/scripts/analyze_cka_pair.py configs/revision/exp4/cka_cross_seed/pt1-7_vs_pt1-7_seed2/layer3.yaml --overwrite
